base_url = "https://swinalwaghmare.github.io"

title = "Swinal Waghmare"
description = "AWS Cloud & DevOps Engineer"

compile_sass = true
build_search_index = true
generate_feeds = true

theme = "terminus"

taxonomies = [
    { name = "tags" }
]
[extra]
close_responsive_menu_on_resize = true
favicon_emoji = "☁️"
feed_icon = true
layout = "center"
show_default_author = false

main_menu = [
    { name = "home", url = "", trailing_slash = false },
    { name = "about", url = "about", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "skills", url = "skills", trailing_slash = true },
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "resume", url = "resume", trailing_slash = true },
    { name = "contact", url = "contact", trailing_slash = true },
]

socials = [
    { name = "email", url = "mailto:your-email@example.com" },
    { name = "github", url = "https://github.com/swinalwaghmare" },
    { name = "linkedin", url = "https://www.linkedin.com/in/YOUR-LINKEDIN-ID" },
]
